### PR TITLE
fix: resolve issue with saving output using full file paths

### LINKED ISSUE #1745: Error saving output on windows with full file paths instead of relative
**Description**

When trying to generate types on Windows and using a full filepath as the output it will error. It does not have the same issue for the input path. If you change the output path to something like `./output.d.ts` or `../output.d.ts` it seems to handle those fine.

The issue seems to be here where you are trying to create a new URL based on the output file but trying to prefix it with `.` which will error when given a full path instead of a relative path.
https://github.com/openapi-ts/openapi-typescript/blob/45cea6b21ae54cc7408174fd35c405d21fcd6044/packages/openapi-typescript/bin/cli.js#L205-L207

```
 npx openapi-typescript C:\Users\User\Desktop\swagger.json -o C:\Users\User\Desktop\output.d.ts
✨ openapi-typescript 7.0.2
node:internal/url:797
    this.#updateContext(bindingUrl.parse(input, base));
                                   ^

TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at main (file:///O:/.packageCache/npm/_npx/21d31b7563e6adbc/node_modules/openapi-typescript/bin/cli.js:206:20) {
  code: 'ERR_INVALID_URL',
  input: '.',
  base: 'c:\\Users\\User\\Desktop\\output.d.ts'
}
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.2`                      |
| Node.js              | `20.15.0`                      |
| OS + version         | `Windows 11` |

**Reproduction**

Try to generate a types file with a full filepath on Windows such as `C:\Users\User\Desktop\output.d.ts`
```
 npx openapi-typescript C:\Users\User\Desktop\swagger.json -o C:\Users\User\Desktop\output.d.ts
```

**Expected result**

It shouldn't error and should support the path like any other

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by phk422**
## Changes

Fix #1745 

## How to Review

Tests added; tests should pass

## Checklist

- [ ] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [ ] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

File: packages/openapi-typescript/bin/cli.js [hunk 1]
```diff
@@ -78,6 +78,18 @@ const flags = parser(args, {
   },
 });
 
+/**
+ * Normalize the output path into a file URL.
+ * @param {string} output - The output path to be transformed.
+ * @returns {URL} The transformed file URL.
+ */
+function normalizeOutput(output) {
```
Comment (drwpow) [inline packages/openapi-typescript/bin/cli.js:86]: This is a good helper, thank you!

**Review by drwpow — APPROVED** [review]
Thank you!
