### PR TITLE
Fix 0.10.0 errors

### LINKED ISSUE #1715: Upgrading to 0.10.0 results in Failed to execute 'fetch' on 'Window'
**Description**

Upgraded to 0.10.0 (and 7.0.0 of openapi-typescript). Perform `.POST(..)` method and receive:

```
Failed to execute 'fetch' on 'Window': The `duplex` member must be specified for a request with a streaming body

at coreFetch (openapi-fetch.js?v=c62ec3c6:100:26)
```

**Reproduction**

As above, previously working POST request on 0.9.0, upgrade to latest 0.10.0. Execute same POST request

**Expected result**

To not throw.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1715 and #1712. Adds Playwright tests to catch client behavior that doesn’t exist in Node’s `fetch()` implementation.

## How to Review

- Tests added; tests should pass

## Checklist

- [x] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [ ] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

File: packages/openapi-fetch/src/index.js [hunk 1]
```diff
@@ -84,56 +90,63 @@ export default function createClient(clientOptions) {
...
-          id,
-        });
-        if (result) {
-          if (!(result instanceof Request)) {
-            throw new Error("onRequest: must return new Request() when modifying the request");
+    if (middlewares.length) {
+      id = randomID();
+
+      // middleware (request)
+      options = Object.freeze({
```
Comment (drwpow) [inline packages/openapi-fetch/src/index.js:101]: Micro-optimization: don’t run certain codepaths if no middleware loaded

File: packages/openapi-fetch/test/fixtures/e2e/app.ts [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+import type { paths } from "./e2e.d.ts";
+
+const client = createClient<paths>({
+  baseUrl: "/api/v1",
+});
+
+/**
+ * Test 1: GET /api/v1/get
+ */
+async function testGet() {
```
Comment (drwpow) [inline packages/openapi-fetch/test/fixtures/e2e/app.ts:11]: New tests that get loaded in a true browser environment. Not comprehensive, but we at least have:

- GET request (no body)
- POST request (with body)
- POST request with multi-part/form data

File: packages/openapi-fetch/package.json [hunk 3]
```diff
@@ -54,15 +54,17 @@
     "build:cjs": "esbuild --bundle src/index.js --format=cjs --outfile=dist/cjs/index.cjs && cp dist/index.d.ts dist/cjs/index.d.cts",
     "format": "biome format . --write",
     "lint": "biome check .",
-    "generate-types": "openapi-typescript test/fixtures/api.yaml -o test/fixtures/api.d.ts",
+    "generate-types": "openapi-typescript -c test/redocly.yaml",
```
Comment (drwpow) [inline packages/openapi-fetch/package.json:57]: Use fancy new 7.x ability to generate multiple schemas with one config file

File: packages/openapi-fetch/src/index.js [hunk 4]
```diff
@@ -84,56 +90,63 @@ export default function createClient(clientOptions) {
...
+            request = result;
           }
-          request = result;
         }
       }
     }
 
     // fetch!
-    let response = await fetch(request.url, request);
+    let response = await fetch(request);
```
Comment (drwpow) [inline packages/openapi-fetch/src/index.js:128]: This is the central error fix—`Request` can’t be substituted for `RequestInit` in every environment. Trying to hack around this results in even nastier code when you consider different browsers implement different stages of `RequestInit` and experimental APIs under-the-hood. This library shouldn’t take on any of that burden, and instead use a `Request` object which is universal and spec-compliant.

File: packages/openapi-fetch/src/index.d.ts [hunk 5]
```diff
@@ -15,7 +15,7 @@ export interface ClientOptions extends Omit<RequestInit, "headers"> {
   /** set the common root URL for all API requests */
   baseUrl?: string;
   /** custom fetch (defaults to globalThis.fetch) */
-  fetch?: (input: string, init?: RequestInit) => Promise<Response>;
+  fetch?: (input: Request) => Promise<Response>;
```
Comment (drwpow) [inline packages/openapi-fetch/src/index.d.ts:18]: This is _technically_ a breaking change, but since it was a breaking change from `0.9.0` I’m just going to pretend this was an accidental regression and never happened 🙈

File: package.json [hunk 6]
```diff
@@ -12,14 +12,18 @@
     "lint": "pnpm run -r --parallel --aggregate-output lint",
     "format": "pnpm run -r --parallel --aggregate-output format",
     "test": "pnpm run -r --parallel --aggregate-output test",
+    "test-e2e": "pnpm run -r --parallel --aggregate-output test-e2e",
```
Comment (drwpow) [inline package.json:15]: ⚠️ **VERY** important that this is not run as part of `"test"`. We don’t need to run this multiple times in different OSs and and different Node versions. We only need to run this **ONCE** in a single environment (Ubuntu, Node latest because that’s the cheapest/fastest).
